In [5]:
import pandas as pd

In [11]:
#Đọc dữ liệu
Minerals_Database = pd.read_csv('Minerals_Database.csv')

#Lọc các cột cần dùng và các hàng có cả 3 giá trị Magnesium, Calcium, Iron bằng 0
Minerals_Database_filter = Minerals_Database[['Name', 'Magnesium', 'Calcium', 'Iron', 'Molar Mass']]
Minerals_Database_use = Minerals_Database_filter[(Minerals_Database_filter['Magnesium'] > 0) 
                                                | (Minerals_Database_filter['Calcium'] > 0) 
                                                | (Minerals_Database_filter['Iron'] > 0)]
Minerals_Database_sort = Minerals_Database_use.sort_values(by=['Magnesium'], ascending=False)

top_5_minerals = Minerals_Database_sort.head(5)
# Hiển thị kết quả sau khi lọc
display(top_5_minerals)

                  Name  Magnesium  Calcium  Iron   Molar Mass
873       Antigorite-T       48.0      0.0   0.0  4473.458800
66          Antigorite       32.0      0.0   0.0  2870.558900
872       Antigorite-M       26.0      0.0   0.0  2305.079000
902   Arrojadite-(KNa)       13.0      1.0  14.0  2754.630123
1603       Gottardiite       12.0     12.0  11.0  3305.874045

In [37]:
# Tính phần trăm của Magnesium, Calcium và Iron trong Molar Mass
Minerals_Database_sort['Mg_Percentage'] = (Minerals_Database_sort['Magnesium']*24 / Minerals_Database_sort['Molar Mass']) * 100
Minerals_Database_sort['Ca_Percentage'] = (Minerals_Database_sort['Calcium']*40  / Minerals_Database_sort['Molar Mass']) * 100
Minerals_Database_sort['Fe_Percentage'] = (Minerals_Database_sort['Iron']* 56 / Minerals_Database_sort['Molar Mass']) * 100

# Hiển thị kết quả với phần trăm của Mg, Ca, Fe trong Molar Mass
top_5_minerals_percentage = Minerals_Database_sort[['Name', 'Mg_Percentage', 'Ca_Percentage', 'Fe_Percentage']].head(5)
display(top_5_minerals_percentage)

                  Name  Mg_Percentage  Ca_Percentage  Fe_Percentage
873       Antigorite-T      25.751886       0.000000       0.000000
66          Antigorite      26.754372       0.000000       0.000000
872       Antigorite-M      27.070656       0.000000       0.000000
902   Arrojadite-(KNa)      11.326385       1.452101      28.461171
1603       Gottardiite       8.711766      14.519609      18.633499

In [39]:
# Tính phần trăm MgO, CaO và FeO
Minerals_Database_sort['MgO_Percentage'] = Minerals_Database_sort['Mg_Percentage'] * 1.092
Minerals_Database_sort['CaO_Percentage'] = Minerals_Database_sort['Ca_Percentage'] * 0.785
Minerals_Database_sort['FeO_Percentage'] = Minerals_Database_sort['Fe_Percentage'] * 0.859

# Tính phần trăm CO2 từ các oxit
Minerals_Database_sort['CO2'] = (Minerals_Database_sort['MgO_Percentage'] 
                                              + Minerals_Database_sort['CaO_Percentage'] 
                                              + Minerals_Database_sort['FeO_Percentage'])

# Hiển thị kết quả với phần trăm CO2
top_5_minerals_CO2 = Minerals_Database_sort[['Name', 'CO2']].head(5)
display(top_5_minerals_CO2)

                  Name        CO2
873       Antigorite-T  28.121059
66          Antigorite  29.215774
872       Antigorite-M  29.561156
902   Arrojadite-(KNa)  37.956457
1603       Gottardiite  36.917317